config/routes.rb
Rails.application.routes.draw do
  resources :tops, only: [:index]
  resources :users, only:[:index, :new, :create, :destroy]
  resources :tours
  root 'tops#index'
  get 'login', to:'tops#login'
  post 'login', to:'tops#login'
  get 'tops/logout'
  get 'tag/show'

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :tour
  mount_uploader :img, ImageUploader
  # serialize :img, JSON
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images #アトリビュート設定
  
  is_impressionable counter_cache: true
  
  geocoded_by :address
  after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tours, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :login_check
  
  private
  def current_user
    if session[:login_uid]
      User.find_by(uid: session[:login_uid])
    end
  end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
  def show
    @tag = params[:format]
    @tour = Tour.where(tag: @tag).page(params[:page]).per(10).order(:id)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @users = User.all
    @rank = Tour.order('impressions_count DESC').take(3)
  end
  
  def login_form
  end
  
  def login
    user = User.find_by(uid: params[:uid])
    if user && BCrypt::Password.new(user.password) == params[:password]
      session[:login_uid] = user[:uid]
      redirect_to root_path
    else
      render 'tops/login'
    end
  end

  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  impressionist :actions=> [:show]
  
  def index
    @tours = Tour.page(params[:page]).per(10).order(:id)
  end

  def show
    @tour = Tour.find(params[:id])
    @image = Image.where(tour_id: params[:id])
    impressionist(@tour, nil, unique: [:session_hash])
  end

  def new
    @tour = Tour.new
    @image = Image.new
    3.times { @tour.images.build }
  end
  def create
    @tour = Tour.create(create_params)
    @tour.user_id = User.find_by(uid: session[:login_uid]).id
    @tour.save
    
    redirect_to tour_path(@tour)
  end

  def edit
    @tour = Tour.find(params[:id])
  end
  def update
    tour = Tour.find(params[:id])
    tour.update(update_params)
    
    redirect_to tour_path(tour)
  end

  def destroy
    tour = Tour.find(params[:id])
    tour.destroy
    redirect_to tours_path
  end
  
  private
  def create_params
    params.require(:tour).permit(:title, :tag, :area, :address, :url, :text, images_attributes: [:img])
  end
  
  def update_params
    params.require(:tour).permit(:title, :tag, :area, :address, :url, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find_by(uid: session[:login_uid]).id
    @tours = Tour.where(user_id: @user).page(params[:page]).per(10).order(:id)
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new(
      uid: params[:user][:uid],
      password: BCrypt::Password.create(params[:user][:password]))
      @user.save
      redirect_to login_path
  end
  
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fukuokamap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id = "container">
    <div id = "header">
      <%= render "header" %>
    </div>
    <div id = "content">
      <%= yield %>
    </div>
    <div id = "footer">
      <%= render "footer" %>
      <p> &#169; 2019 福岡探索MAP	</p>
    </div>
  </div>
</body>
</html>

app/views/tag/_header.html.erb
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <ul>
    <%= link_to tops_path do %>
      <li><h2>福岡探索MAP</h2></li>
    <% end %>
    <li style="flex-grow: 2;"><i class="fas fa-tags fa-3x"></i><br/>TAG</li>
    <%= link_to '自然', tag_show_path('自然'), :style=>"color:white;" %>&ensp;
    <%= link_to 'まち', tag_show_path('まち'), :style=>"color:white;" %>&ensp;
    <%= link_to '公園', tag_show_path('公園'), :style=>"color:white;" %>&ensp;
    <%= link_to '歴史', tag_show_path('歴史'), :style=>"color:white;" %>&ensp;
    <%= link_to '伝統文化・祭', tag_show_path('伝統文化・祭'), :style=>"color:white;" %>&ensp;
    <%= link_to '施設', tag_show_path('施設'), :style=>"color:white;" %>&ensp;
    <%= link_to '食', tag_show_path('食'), :style=>"color:white;" %>&ensp;
    <%= link_to 'スポーツ', tag_show_path('スポーツ'), :style=>"color:white;" %>
    <% unless session[:login_uid] %>
    <%= link_to login_path do %>
    <li><i class="fas fa-lock fa-3x"></i><br/>LOGIN</li>
    <% end %>
    <% else %>
    <%= link_to new_tour_path do %>
    <li><i class="fas fa-pencil-alt fa-3x"></i><br/>UPLOAD</li>
    <% end %>
    <%= link_to users_path do %>
    <li><i class="fas fa-user fa-3x"></i><br/>MY PAGE</li>
    <% end %>
    <%= link_to tops_logout_path do %>
    <li><i class="fas fa-lock-open fa-3x"></i><br/>LOGOUT</li>
    <% end %>
    <% end %>
    
  </ul>

app/views/tag/show.html.erb
<h1>～絞り込みタグ：<%= @tag %>～</h1>

<div class="main">
  <div class="contents-wrap1">
<% @tour.each do |t| %>
<div class="contents-box1">
  <%= link_to  tour_path(t) do %>
  <img>
  <% unless t.images.empty? %>
    <%= image_tag t.images[0].img, :height => '150' %>
  <% end %>
   </img>
  <h2><%= t.title %></h2>
  <%= t.updated_at.strftime('%Y/%m/%d') %>&ensp;|&ensp;
  <%= User.find_by(id: t.user_id).uid %>&ensp;|&ensp;
  <%= t.tag %>&ensp;|&ensp;
  <%= t.impressionist_count %>views
  <% end %>
  </div>
<% end %>
</div>

<%= paginate(@tour) %>
<br/>
<br/>
  
<%= link_to tours_path  do %>
<div class="btn">
    <p>TOPICSへ</p>
</div>
<% end %>
&ensp;&ensp;&ensp;&ensp;
<%= link_to  root_path do %>
    <div class="btn">
    <p>TOPへ</p>
    </div>
<% end %>

</div>

app/views/tops/index.html.erb
<header id="top_index">
  <div class="headerImg1">
    <img src="/assets/img1.jpg">
  </div>
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <ul>
    <%= link_to tops_path do %>
      <li><h2>福岡探索MAP</h2></li>
    <% end %>
    <li style="flex-grow: 2;"><i class="fas fa-tags fa-3x"></i><br/>TAG</li>
    <%= link_to '自然', tag_show_path('自然'), :style=>"color:white;" %>&ensp;
    <%= link_to 'まち', tag_show_path('まち'), :style=>"color:white;" %>&ensp;
    <%= link_to '公園', tag_show_path('公園'), :style=>"color:white;" %>&ensp;
    <%= link_to '歴史', tag_show_path('歴史'), :style=>"color:white;" %>&ensp;
    <%= link_to '伝統文化・祭', tag_show_path('伝統文化・祭'), :style=>"color:white;" %>&ensp;
    <%= link_to '施設', tag_show_path('施設'), :style=>"color:white;" %>&ensp;
    <%= link_to '食', tag_show_path('食'), :style=>"color:white;" %>&ensp;
    <%= link_to 'スポーツ', tag_show_path('スポーツ'), :style=>"color:white;" %>
    <% unless session[:login_uid] %>
    <%= link_to login_path do %>
    <li><i class="fas fa-lock fa-3x"></i><br/>LOGIN</li>
    <% end %>
    <% else %>
    <%= link_to new_tour_path do %>
    <li><i class="fas fa-pencil-alt fa-3x"></i><br/>UPLOAD</li>
    <% end %>
    <%= link_to users_path do %>
    <li><i class="fas fa-user fa-3x"></i><br/>MY PAGE</li>
    <% end %>
    <%= link_to tops_logout_path do %>
    <li><i class="fas fa-lock-open fa-3x"></i><br/>LOGOUT</li>
    <% end %>
    <% end %>
    
  </ul>
</header>

<div class="main">
  <div class="ber">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400i" rel="stylesheet">   
    <span class="title"> FUKUOKA </span>
  </div>
  <p>
      九州・アジアの玄関口、「福岡」。<br/>
      九州の中心として賑わうエネルギッシュな街に開放的でフレンドリーな博多っ子。<br/>
      豊かな食・伝統的な文化・恵まれた自然・暮らしやすい生活環境。<br/>
      ますますパワーアップする福岡の魅力をお届け！
  </p>
 
  <div class="ber">
    <span class="title"> TOPICS </sapn>
  </div>
   <%= link_to  tours_path do %>
    <nav>
    <p>all</p>
    </nav>
   <% end %>
<br/>

<div class="contents-wrap">
  <% @rank.each.with_index(1) do |rank, i| %>
  <div class="contents-box">
     NO. <%=  i %>
     <%= link_to tour_path(rank) do %>
     <img>
     <% unless rank.images.empty? %>
       <%= image_tag rank.images[0].img, :height => '150' %>
     <% end %>
     </img>
     <h2><%= rank.title %></h2>
     <%= rank.updated_at.strftime('%Y/%m/%d') %>&ensp;|&ensp;
     <%= User.find_by(id: rank.user_id).uid %>&ensp;|&ensp;
     <%= rank.tag %>&ensp;|&ensp;
     <%= rank.impressionist_count %> views
    <% end %>
    </div>
  <% end %>
  
</div>

</div>

app/views/tops/login.html.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

<!------ Include the above in your HEAD tag ---------->
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <ul>
    <li>福岡探索MAP</li>
    <li style="flex-grow: 2;"><i class="fas fa-tags fa-3x"></i><br/>TAG</li>
    <% unless session[:login_uid] %>
    <%= link_to login_path do %>
    <li><i class="fas fa-lock fa-3x"></i><br/>LOGIN</li>
    <% end %>
    <% else %>
    <%= link_to new_tour_path do %>
    <li><i class="fas fa-pencil-alt fa-3x"></i><br/>UPLOAD</li>
    <% end %>
    <%= link_to users_path do %>
    <li><i class="fas fa-user fa-3x"></i><br/>MY PAGE</li>
    <% end %>
    <%= link_to tops_logout_path do %>
    <li><i class="fas fa-lock-open fa-3x"></i><br/>LOGOUT</li>
    <% end %>
    <% end %>
    
  </ul>

	<div class="login-container">
	    <h1>福岡探索MAP</h1>
            <div id="output"></div>
            <div class="form-box">
                <form action="/login" method="">
                    <%= text_field_tag :uid , nil, placeholder:"ID"%>
                    <%= password_field_tag :password , nil, placeholder:"password"%>
                    <button class="btn btn-info btn-block login" type="submit">Login</button>
                </form>
                <form action="users/new" method="">
                    <button class="btn btn-info btn-block login" type="submit">Sign Up</button>
                </form>
            </div>
    </div>
        <br/>
        <br/>

<%= link_to  root_path do %>
    <div class="btn">
    <p>TOPへ</p>
    </div>
<% end %>

app/views/tops/logout.html.erb
<h1>Tops#logout</h1>
<p>Find me in app/views/tops/logout.html.erb</p>

app/views/tours/_header.html.erb
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <ul>
    <%= link_to tops_path do %>
      <li><h2>福岡探索MAP</h2></li>
    <% end %>
    <li style="flex-grow: 2;"><i class="fas fa-tags fa-3x"></i><br/>TAG</li>
    <%= link_to '自然', tag_show_path('自然'), :style=>"color:white;" %>&ensp;
    <%= link_to 'まち', tag_show_path('まち'), :style=>"color:white;" %>&ensp;
    <%= link_to '公園', tag_show_path('公園'), :style=>"color:white;" %>&ensp;
    <%= link_to '歴史', tag_show_path('歴史'), :style=>"color:white;" %>&ensp;
    <%= link_to '伝統文化・祭', tag_show_path('伝統文化・祭'), :style=>"color:white;" %>&ensp;
    <%= link_to '施設', tag_show_path('施設'), :style=>"color:white;" %>&ensp;
    <%= link_to '食', tag_show_path('食'), :style=>"color:white;" %>&ensp;
    <%= link_to 'スポーツ', tag_show_path('スポーツ'), :style=>"color:white;" %>
    <% unless session[:login_uid] %>
    <%= link_to login_path do %>
    <li><i class="fas fa-lock fa-3x"></i><br/>LOGIN</li>
    <% end %>
    <% else %>
    <%= link_to new_tour_path do %>
    <li><i class="fas fa-pencil-alt fa-3x"></i><br/>UPLOAD</li>
    <% end %>
    <%= link_to users_path do %>
    <li><i class="fas fa-user fa-3x"></i><br/>MY PAGE</li>
    <% end %>
    <%= link_to tops_logout_path do %>
    <li><i class="fas fa-lock-open fa-3x"></i><br/>LOGOUT</li>
    <% end %>
    <% end %>
    
  </ul>

app/views/tours/edit.html.erb
<h1>〜投稿記事〜</h1>
<%= form_for @tour ,html: {class: 'topBefore', id: 'form'} do |f| %>
  <%= f.label :area, "エリア" %>
  <%= f.select :area, [["福岡","福岡"],["北九州","北九州"],["筑豊","筑豊"],["筑後","筑後"]], :placeholder => 'エリア' , :id => "input" %><br>
  <%= f.label :tag, "タグ" %>
  <%= f.select :tag, [["自然","自然"],["まち","まち"],["公園","公園"],["歴史","歴史"],["伝統文化・祭","伝統文化・祭"],["施設","施設"],["食","食"],["スポーツ","スポーツ"]] %>
  <%= f.text_field :title, :placeholder => "タイトル" , :id => "input"%><br>
  <%= f.text_field :address, :placeholder => 'アドレス' , :id => "input" %><br>
  <%= f.text_field :url, :placeholder => 'URL' , :id => "input" %><br>
  <%= f.text_area :text, :placeholder => '紹介文' , :id => "textarea" %><br>
  
  <%= f.submit "更新", :id => "submit" %>
  <%= f.submit "クリア", type: :reset , :id => "clear"%>
<% end %>
<br/>
<br/>
<br/>
<%= link_to  tours_path do %>
    <div class="btn">
    <p>TOPICSへ</p>
    </div>
   <% end %>

app/views/tours/index.html.erb
<h1>～TOPICS～</h1>
<div class="main">
  
 <div class="contents-wrap1">
<% @tours.each do |t| %>
<div class="contents-box1">
<%= link_to  tour_path(t) do %>
  
  <img>
  <% unless t.images.empty? %>
    <%= image_tag t.images[0].img, :height => '150' %>
  <% end %>
  </img>
  <h2><%= t.title %></h2>
  <%= t.updated_at.strftime('%Y/%m/%d') %>&ensp;|&ensp;
  <%= User.find_by(id: t.user_id).uid %>&ensp;|&ensp;
  <%= t.tag %>&ensp;|&ensp;
  <%= t.impressionist_count %>views

<% end %>
</div>
<% end %>
</div>
</br><p>
  <%= paginate(@tours) %>
</p><br/>

<%= link_to  root_path do %>
    <div class="btn">
    <p>TOPへ</p>
    </div>
   <% end %>


</div>

app/views/tours/new.html.erb
<h1>〜投稿記事〜</h1>
<%= form_for @tour ,html: {class: 'topBefore', id: 'form'} do |f| %>
<%= f.label :area, "エリア" %>
<%= f.select :area, [["福岡","福岡"],["北九州","北九州"],["筑豊","筑豊"],["筑後","筑後"]]%><br>
   <%= f.label :tag, "タグ" %>
   <%= f.select :tag, [["自然","自然"],["まち","まち"],["公園","公園"],["歴史","歴史"],["伝統文化・祭","伝統文化・祭"],["施設","施設"],["食","食"],["スポーツ","スポーツ"]] %>
   
  <%= f.text_field :title, :placeholder => 'タイトル' , :id => "input" %><br/>
  <%= f.text_field :address, :placeholder => '住所' , :id => "input" %><br>
  <%= f.text_field :url, :placeholder => 'URL' , :id => "input" %><br>
  <%= f.text_area :text, :placeholder => '紹介文' , :id => "textarea" %><br>
  <div id = "picture">
  <%= f.fields_for :images do |image| %>
    <%= image.file_field :img , :id => "file" %>
  <% end %>
  </div>
  <%= f.submit "投稿", :id => "submit" %>
  <%= f.submit "クリア", type: :reset , :id => "clear"%>
  
<% end %>
<br/>
<br/>
<%= link_to  root_path do %>
    <div class="btn">
    <p>TOPへ</p>
    </div>
   <% end %>

app/views/tours/show.html.erb
<div class="main">
<div id= "grid">
  <div id="mark">
  <div class="Ribbon">
    <span class="Ribbon-inner"></span>
  </div>
  </div>
  <div id="date">
    <p><% if @tour.created_at.to_i == @tour.updated_at.to_i %>
      <%= @tour.created_at.strftime('%Y/%m/%d') %>
    <% else %>
      <%= @tour.updated_at.strftime('%Y/%m/%d') %>
    <% end %>&ensp;|&ensp;
    <%= User.find_by(id: @tour.user_id).uid %>&ensp;|&ensp;
    <%= @tour.tag %>&ensp;|&ensp;
    <%= @tour.impressionist_count %> views 

    </p>
  </div>
  <div id="title">
    <div class="tour_title"><%= @tour.title %></div>
  </div>
  <div id="text">
    <p><%= @tour.text %></p>
  </div>
  <div id="info">
    <table>
　　<tbody>
　　<tr>
　　<th>住所</th>
　　<td class="data fst">
　　<%= @tour.address %><br>
　　</td>
　　</tr>
　　<tr>
　　<td class="bar" colspan="6"></td>
　　</tr>
　　<tr>
　　<th>URL</th>
　　<td class="data fst">
　　<%= link_to @tour.url, @tour.url %>
　　</td>
　　</tr>
　　</tbody>
　　</table>
  </div>
</div>

<p>
  <% unless @tour.images.empty? %>
    <% i = 0 %>
    <% while @tour.images.size > i do %>
      <%= image_tag @tour.images[i].img, :height => '300' %>
      <% i = i + 1 %>
    <% end %>
  <% end %>
</p>

<% if session[:login_uid] %>
<div class="edit">
    <% if @tour.user_id == User.find_by(uid: session[:login_uid]).id %>
      <%= link_to  edit_tour_path(@tour) do %>
  <nav>
    <p>編集</p>
  </nav>
      <% end %>
    <% end %>
</div>
<% end %>
<br/>
<br/>
<br/>
<%= link_to tours_path  do %>
<div class="btn">
    <p>TOPICSへ</p>
    </div>
<% end %>
</div>

app/views/users/_header.html.erb
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <ul>
    <%= link_to tops_path do %>
      <li><h2>福岡探索MAP</h2></li>
    <% end %>
    <li style="flex-grow: 2;"><i class="fas fa-tags fa-3x"></i><br/>TAG</li>
    <%= link_to '自然', tag_show_path('自然'), :style=>"color:white;" %>&ensp;
    <%= link_to 'まち', tag_show_path('まち'), :style=>"color:white;" %>&ensp;
    <%= link_to '公園', tag_show_path('公園'), :style=>"color:white;" %>&ensp;
    <%= link_to '歴史', tag_show_path('歴史'), :style=>"color:white;" %>&ensp;
    <%= link_to '伝統文化・祭', tag_show_path('伝統文化・祭'), :style=>"color:white;" %>&ensp;
    <%= link_to '施設', tag_show_path('施設'), :style=>"color:white;" %>&ensp;
    <%= link_to '食', tag_show_path('食'), :style=>"color:white;" %>&ensp;
    <%= link_to 'スポーツ', tag_show_path('スポーツ'), :style=>"color:white;" %>
    <% unless session[:login_uid] %>
    <%= link_to login_path do %>
    <li><i class="fas fa-lock fa-3x"></i><br/>LOGIN</li>
    <% end %>
    <% else %>
    <%= link_to new_tour_path do %>
    <li><i class="fas fa-pencil-alt fa-3x"></i><br/>UPLOAD</li>
    <% end %>
    <%= link_to users_path do %>
    <li><i class="fas fa-user fa-3x"></i><br/>MY PAGE</li>
    <% end %>
    <%= link_to tops_logout_path do %>
    <li><i class="fas fa-lock-open fa-3x"></i><br/>LOGOUT</li>
    <% end %>
    <% end %>
    
  </ul>

app/views/users/index.html.erb
<h1>〜マイページ〜</h1>
投稿数：<%= @tours.count %><br>

<div class="main">
   <div class="contents-wrap1">
<% @tours.each do |t| %>
<div class="contents-box1">
  <%= link_to  tour_path(t) do %>
  <img>
  <% unless t.images.empty? %>
    <%= image_tag t.images[0].img, :height => '150' %>
  <% end %>

  </img>
  <h2><%= t.title %></h2>
  <%= t.updated_at.strftime('%Y/%m/%d') %>&ensp;|&ensp;
  <%= User.find_by(id: t.user_id).uid %>&ensp;|&ensp;
  <%= t.tag %>&ensp;|&ensp;
  <%= t.impressionist_count %>views
  <% end %>
  <% if t.user_id == User.find_by(uid: session[:login_uid]).id %>
    <h4><%= link_to "削除", tour_path(t), method: :delete  %></h4>
  <% end %>
  
  </div>
<% end %>
</div>
<%= paginate(@tours) %>
<br/>
<br/>
  
<%= link_to tours_path  do %>
<div class="btn">
    <p>TOPICSへ</p>
</div>
<% end %>
&ensp;&ensp;&ensp;&ensp;
<%= link_to  root_path do %>
    <div class="btn">
    <p>TOPへ</p>
    </div>
<% end %>

</div>

app/views/users/new.html.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">


	<div class="login-container">
	    <h1>福岡探索MAP</h1>
            <div id="output"></div>
            <div class="form-box">
                <%= form_for @user do |u| %>
                  <% u.label :uid, 'ユーザーID' %>
                  <%= u.text_field :uid , placeholder: 'ID' %>
                  <% u.label :password, 'パスワード' %>
                  <%= u.password_field :password , placeholder: 'password' %>
                  <button class="btn btn-info btn-block login" type="submit">Sign Up</button>
                <% end %>
            </div>
    </div>